# Generated by Django 3.1.3 on 2020-12-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название подарка')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gifts/', verbose_name='Фото')),
            ],
        ),
    ]
