# Generated by Django 3.1.3 on 2020-12-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0007_usergift_is_stream_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
