# Generated by Django 3.1.3 on 2020-12-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0009_streamdonater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergift',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
