# Generated by Django 3.1.3 on 2021-08-12 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0010_auto_20201227_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='gifts/', verbose_name='Иконка')),
                ('is_for_vip', models.BooleanField(default=False, verbose_name='Для VIP?')),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='gift.category'),
        ),
    ]
