# Generated by Django 3.1.3 on 2021-08-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0012_category_order_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('order_num',)},
        ),
        migrations.AddField(
            model_name='gift',
            name='is_with_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='GiftAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сообщение')),
                ('file', models.FileField(blank=True, null=True, upload_to='gifts_files/')),
                ('gift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='gift.gift')),
            ],
        ),
    ]
