# Generated by Django 3.1.3 on 2021-08-23 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0013_auto_20210823_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftanswer',
            name='gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='gift.usergift'),
        ),
    ]
