# Generated by Django 3.1.3 on 2021-08-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0015_auto_20210823_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='giftanswer',
            old_name='gift',
            new_name='user_gift',
        ),
    ]
