# Generated by Django 3.1.3 on 2021-08-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0016_auto_20210823_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftAnswer',
        ),
    ]
