# Generated by Django 3.1.3 on 2021-08-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0017_delete_giftanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergift',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to='gifts_files/'),
        ),
        migrations.AddField(
            model_name='usergift',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
