# Generated by Django 3.1.3 on 2021-08-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0018_auto_20210823_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergift',
            name='answer_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
