# Generated by Django 3.1.3 on 2021-08-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20210802_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='show_at_index',
            field=models.BooleanField(default=False),
        ),
    ]
