# Generated by Django 3.1.3 on 2020-12-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_auto_20201210_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='is_acrhived',
            new_name='is_archived',
        ),
    ]
