# Generated by Django 3.1.3 on 2021-03-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_auto_20210323_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamlike',
            old_name='post',
            new_name='stream',
        ),
    ]
