# Generated by Django 3.1.3 on 2021-01-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='От'),
        ),
        migrations.AlterField(
            model_name='feedbackform',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Email'),
        ),
    ]
