# Generated by Django 3.1.3 on 2020-12-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_stream_chat',
            field=models.BooleanField(default=False),
        ),
    ]
