# Generated by Django 3.1.3 on 2020-12-17 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20201210_1723'),
        ('chat', '0002_chat_is_stream_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='stream.stream'),
        ),
    ]
