# Generated by Django 3.1.3 on 2020-12-20 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_auto_20201210_1723'),
        ('chat', '0003_chat_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stream_chat', to='stream.stream'),
        ),
    ]
