# Generated by Django 3.1.3 on 2021-01-05 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20201220_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='StikerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название группы')),
                ('is_for_vip', models.BooleanField(default=False, verbose_name='Для VIP?')),
            ],
            options={
                'verbose_name': 'Группа стикеров',
                'verbose_name_plural': 'Группы стикеров',
            },
        ),
        migrations.CreateModel(
            name='Stiker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat/', verbose_name='Изображение')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.stikergroup')),
            ],
            options={
                'verbose_name': 'Стикер',
                'verbose_name_plural': 'Стикеры',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='stiker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.stiker', verbose_name='Стикер'),
        ),
    ]
