# Generated by Django 3.1.3 on 2021-01-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20210105_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stiker',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stikers', to='chat.stikergroup'),
        ),
    ]
