# Generated by Django 3.1.3 on 2021-02-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20210108_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_translate',
            field=models.TextField(blank=True, null=True, verbose_name='Перевод'),
        ),
    ]
