# Generated by Django 3.1.3 on 2021-03-31 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_traslatekey'),
    ]

    operations = [
        migrations.AddField(
            model_name='stikergroup',
            name='is_for_vip_level',
            field=models.IntegerField(default=1, verbose_name='Для ВИП уровня'),
        ),
    ]
