# Generated by Django 3.1.3 on 2021-02-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='name_slug',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Название'),
        ),
    ]
