# Generated by Django 3.1.3 on 2020-11-26 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendlist',
            old_name='friend_list_owner',
            new_name='user',
        ),
        migrations.CreateModel(
            name='FriendApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_list', models.ManyToManyField(related_name='apply_list', to=settings.AUTH_USER_MODEL, verbose_name='Запросы в друзья')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
        ),
    ]
