# Generated by Django 3.1.3 on 2020-11-29 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_auto_20201128_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendapply',
            options={'verbose_name': 'Список заявок в друзья', 'verbose_name_plural': 'Список заявок в друзья'},
        ),
        migrations.AlterModelOptions(
            name='friendlist',
            options={'verbose_name': 'Список друзей', 'verbose_name_plural': 'Список друзей'},
        ),
    ]
