# Generated by Django 3.1.3 on 2020-11-29 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=1, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stream_key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, verbose_name='Ключ стрима'),
        ),
    ]
