# Generated by Django 3.1.3 on 2020-12-01 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201201_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gifts',
        ),
    ]
