# Generated by Django 3.1.3 on 2020-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_gifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Образование'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='Интересы'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests_additional',
            field=models.TextField(blank=True, null=True, verbose_name='Интересы дополнительные'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vip_expire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения аккаунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vip_update',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала аккаунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechatid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='wechatid'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(blank=True, to='user.UserTag'),
        ),
    ]
