# Generated by Django 3.1.3 on 2020-12-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20201206_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stream_key',
            new_name='suid',
        ),
    ]
