# Generated by Django 3.1.3 on 2021-01-08 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20201210_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/bg', verbose_name='Задний фон')),
                ('is_for_vip', models.BooleanField(default=False, verbose_name='Для ВИП?')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.userbg'),
        ),
    ]
