# Generated by Django 3.1.3 on 2021-03-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210108_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vip_rating',
            field=models.IntegerField(default=1, verbose_name='VIP очки профиля'),
        ),
    ]
