# Generated by Django 3.1.3 on 2021-03-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_vip_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='BgGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название группы')),
                ('is_for_vip', models.BooleanField(default=False, verbose_name='Для VIP?')),
                ('is_for_vip_level', models.IntegerField(default=1, verbose_name='Для ВИП уровня')),
            ],
            options={
                'verbose_name': 'Группа бекграундов',
                'verbose_name_plural': 'Группы бекграундов',
            },
        ),
        migrations.AlterModelOptions(
            name='userbg',
            options={'verbose_name': 'Задний фон', 'verbose_name_plural': 'Задние фоны'},
        ),
        migrations.RemoveField(
            model_name='userbg',
            name='is_for_vip',
        ),
        migrations.AddField(
            model_name='user',
            name='vip_level',
            field=models.IntegerField(default=0, verbose_name='VIP Уровень'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vip_rating',
            field=models.IntegerField(default=0, verbose_name='VIP очки профиля'),
        ),
        migrations.AddField(
            model_name='userbg',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='user.bggroup'),
        ),
    ]
