# Generated by Django 3.1.3 on 2021-08-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210331_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_expire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения оплаченного аккунта'),
        ),
        migrations.AddField(
            model_name='user',
            name='pay_start',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала оплаченного аккунта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vip_expire',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения VIP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vip_update',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала VIP'),
        ),
    ]
