# Generated by Django 3.1.3 on 2021-08-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210816_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vip_expire',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vip_update',
        ),
    ]
