# Generated by Django 3.1.3 on 2021-08-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210818_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertag',
            old_name='name',
            new_name='label',
        ),
    ]
